name: heroes_api
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #agregar
  http: ^1.2.2
  drift: ^1.0.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.0
  path: ^1.8.0
  provider: ^6.0.3
  intl: ^0.17.0
  shared_preferences: ^2.0.6 #para shared preferences

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  #agregaar
  drift_dev: ^1.0.0
  build_runner: ^2.1.11

  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/comics.jpeg

#agregar para el icono de la aplicacion
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"